name: Feature Request / 기능 추가 요청
description: Suggest an idea for this project / 새로운 기능에 대한 아이디어를 제안하기
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the current problem and the desired feature / 현존하는 문제점과 원하는 추가 기능에 대하여 설명해주세요
      description: |
        Thank you for your feature request.
        새로운 기능을 제안해주셔서 감사드려요.
    validations:
      required: true
  - type: textarea
    id: desired
    attributes:
      label: Describe the solution you'd like / 문제 해결 방법 혹은 기능 실현 방안
      description: |
        A clear and concise description of what you want to happen.
        문제 해결 방법 혹은 기능을 실현하는 방안에 대해 생각해둔 점이 있다면, 간결하게 설명해주세요.
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered / 또 다른 문제 해결 방법 혹은 기능 실현 방안
      description: |
        A clear and concise description of any alternative solutions or features you've considered.
        부가적인 문제 해결 방법 혹은 기능 실현 방안이 있다면, 간결하게 설명해주세요.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context / 기타
      description: |
        Add any other context about the problem here.
        제안해주신 기능에 대해 더 추가하고 싶은 내용이 있으신가요?
    validations:
      required: false
